"""CRYO Report Generation Tools — PDF, Excel, Charts, Dashboards."""

import json
import logging
import os
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any

from tools.registry import registry

logger = logging.getLogger("cryo.reports")

REPORTS_DIR = Path(os.getenv("CRYO_REPORTS_DIR", "/tmp/cryo-reports"))
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def _gen_filename(prefix: str, ext: str) -> tuple[str, Path]:
    file_id = uuid.uuid4().hex[:12]
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    name = f"{prefix}_{ts}_{file_id}.{ext}"
    return name, REPORTS_DIR / name


# ─── PDF Report ──────────────────────────────────────────────

def _generate_pdf(args: dict, **kw) -> str:
    title = args.get("title", "CRYO Research Report")
    sections = args.get("sections", [])
    summary = args.get("summary", "")

    if not sections and not summary:
        return json.dumps({"error": "Provide 'sections' (list of {heading, content}) or 'summary' text"})

    logger.info("Generating PDF: title=%r sections=%d", title, len(sections))

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
        from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY

        filename, filepath = _gen_filename("report", "pdf")

        doc = SimpleDocTemplate(str(filepath), pagesize=A4,
                                leftMargin=0.8*inch, rightMargin=0.8*inch,
                                topMargin=0.8*inch, bottomMargin=0.8*inch)

        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(
            "CryoTitle", parent=styles["Title"],
            fontSize=24, textColor=HexColor("#00e5c7"),
            spaceAfter=20,
        ))
        styles.add(ParagraphStyle(
            "CryoHeading", parent=styles["Heading1"],
            fontSize=16, textColor=HexColor("#22d3ee"),
            spaceBefore=16, spaceAfter=8,
        ))
        styles.add(ParagraphStyle(
            "CryoBody", parent=styles["Normal"],
            fontSize=10, leading=14, alignment=TA_JUSTIFY,
            spaceAfter=8,
        ))
        styles.add(ParagraphStyle(
            "CryoMeta", parent=styles["Normal"],
            fontSize=8, textColor=HexColor("#6b7d93"),
        ))

        story = []

        # Title page
        story.append(Spacer(1, 1.5*inch))
        story.append(Paragraph(title, styles["CryoTitle"]))
        story.append(Spacer(1, 0.3*inch))
        story.append(Paragraph(
            f"Generated by CRYO — {datetime.now().strftime('%B %d, %Y at %H:%M')}",
            styles["CryoMeta"]
        ))
        story.append(Spacer(1, 0.5*inch))

        if summary:
            story.append(Paragraph("Executive Summary", styles["CryoHeading"]))
            story.append(Paragraph(summary, styles["CryoBody"]))
            story.append(Spacer(1, 0.3*inch))

        # Sections
        for section in sections:
            heading = section.get("heading", "Section")
            content = section.get("content", "")
            story.append(Paragraph(heading, styles["CryoHeading"]))

            # Handle content — could be text or table data
            if isinstance(content, list):
                # Table data: list of dicts
                if content and isinstance(content[0], dict):
                    headers = list(content[0].keys())
                    table_data = [headers]
                    for row in content[:50]:
                        table_data.append([str(row.get(h, ""))[:60] for h in headers])

                    t = Table(table_data, repeatRows=1)
                    t.setStyle(TableStyle([
                        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1c2430")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#00e5c7")),
                        ("FONTSIZE", (0, 0), (-1, -1), 8),
                        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#2a3a4e")),
                        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#0f1419"), HexColor("#151b23")]),
                        ("TEXTCOLOR", (0, 1), (-1, -1), HexColor("#e0e6ed")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("WORDWRAP", (0, 0), (-1, -1), True),
                    ]))
                    story.append(t)
                else:
                    for item in content:
                        story.append(Paragraph(f"• {item}", styles["CryoBody"]))
            else:
                # Plain text — split into paragraphs
                for para in str(content).split("\n\n"):
                    if para.strip():
                        story.append(Paragraph(para.strip(), styles["CryoBody"]))

            story.append(Spacer(1, 0.2*inch))

        doc.build(story)

        logger.info("PDF generated: %s (%d bytes)", filename, filepath.stat().st_size)
        return json.dumps({
            "status": "success",
            "filename": filename,
            "path": str(filepath),
            "size_bytes": filepath.stat().st_size,
            "download_url": f"/api/reports/{filename}",
        })

    except ImportError:
        logger.error("reportlab not installed")
        return json.dumps({"error": "reportlab not installed. Run: pip install reportlab"})
    except Exception as e:
        logger.error("PDF generation failed: %s", e, exc_info=True)
        return json.dumps({"error": f"PDF generation failed: {e}"})


PDF_SCHEMA = {
    "name": "generate_pdf",
    "description": "Generate a professionally formatted PDF research report. Supports title pages, sections with headings, tables, and summaries. Use after gathering research data to create downloadable reports.",
    "parameters": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "description": "Report title (e.g. 'TP53 Variant Analysis Report')"
            },
            "summary": {
                "type": "string",
                "description": "Executive summary paragraph"
            },
            "sections": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "heading": {"type": "string"},
                        "content": {"description": "Text string or array of objects for table data"},
                    },
                },
                "description": "Report sections. Each has a heading and content (text or table data as array of objects)"
            },
        },
        "required": ["title"],
    },
}

registry.register(
    name="generate_pdf",
    toolset="cryo_reports",
    schema=PDF_SCHEMA,
    handler=_generate_pdf,
    check_fn=lambda: True,
    emoji="📑",
)


# ─── Excel Report ────────────────────────────────────────────

def _generate_excel(args: dict, **kw) -> str:
    title = args.get("title", "CRYO Data Export")
    sheets = args.get("sheets", [])

    if not sheets:
        return json.dumps({"error": "Provide 'sheets' (list of {name, data: [{col: val}]})"})

    logger.info("Generating Excel: title=%r sheets=%d", title, len(sheets))

    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

        filename, filepath = _gen_filename("data", "xlsx")
        wb = Workbook()

        # Style constants
        header_font = Font(name="Calibri", size=11, bold=True, color="00E5C7")
        header_fill = PatternFill(start_color="0F1419", end_color="0F1419", fill_type="solid")
        cell_font = Font(name="Calibri", size=10, color="E0E6ED")
        border = Border(
            bottom=Side(style="thin", color="2A3A4E"),
            right=Side(style="thin", color="2A3A4E"),
        )

        for i, sheet_data in enumerate(sheets):
            sheet_name = sheet_data.get("name", f"Sheet{i+1}")[:31]
            data = sheet_data.get("data", [])

            if i == 0:
                ws = wb.active
                ws.title = sheet_name
            else:
                ws = wb.create_sheet(sheet_name)

            if not data:
                continue

            # Headers
            if isinstance(data[0], dict):
                headers = list(data[0].keys())
                for col, header in enumerate(headers, 1):
                    cell = ws.cell(row=1, column=col, value=header)
                    cell.font = header_font
                    cell.fill = header_fill
                    cell.alignment = Alignment(horizontal="center")

                # Data rows
                for row_idx, row_data in enumerate(data[:10000], 2):
                    for col, header in enumerate(headers, 1):
                        val = row_data.get(header, "")
                        cell = ws.cell(row=row_idx, column=col, value=str(val) if not isinstance(val, (int, float)) else val)
                        cell.font = cell_font
                        cell.border = border

                # Auto-width columns
                for col in range(1, len(headers) + 1):
                    max_len = max(
                        len(str(ws.cell(row=r, column=col).value or ""))
                        for r in range(1, min(len(data) + 2, 50))
                    )
                    ws.column_dimensions[ws.cell(row=1, column=col).column_letter].width = min(max_len + 4, 50)

            # Freeze header row
            ws.freeze_panes = "A2"

        wb.save(str(filepath))

        logger.info("Excel generated: %s (%d bytes)", filename, filepath.stat().st_size)
        return json.dumps({
            "status": "success",
            "filename": filename,
            "path": str(filepath),
            "size_bytes": filepath.stat().st_size,
            "download_url": f"/api/reports/{filename}",
            "sheets": [s.get("name", f"Sheet{i+1}") for i, s in enumerate(sheets)],
            "total_rows": sum(len(s.get("data", [])) for s in sheets),
        })

    except ImportError:
        logger.error("openpyxl not installed")
        return json.dumps({"error": "openpyxl not installed. Run: pip install openpyxl"})
    except Exception as e:
        logger.error("Excel generation failed: %s", e, exc_info=True)
        return json.dumps({"error": f"Excel generation failed: {e}"})


EXCEL_SCHEMA = {
    "name": "generate_excel",
    "description": "Generate an Excel spreadsheet with multiple sheets. Each sheet contains tabular data. Use for exporting structured research data, variant lists, drug comparisons, or any tabular output.",
    "parameters": {
        "type": "object",
        "properties": {
            "title": {"type": "string", "description": "Workbook title"},
            "sheets": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string", "description": "Sheet name"},
                        "data": {
                            "type": "array",
                            "items": {"type": "object"},
                            "description": "Array of row objects, e.g. [{gene: 'TP53', significance: 'pathogenic'}]"
                        },
                    },
                },
                "description": "List of sheets with name and data"
            },
        },
        "required": ["sheets"],
    },
}

registry.register(
    name="generate_excel",
    toolset="cryo_reports",
    schema=EXCEL_SCHEMA,
    handler=_generate_excel,
    check_fn=lambda: True,
    emoji="📊",
)


# ─── Chart/Dashboard Generation ──────────────────────────────

def _generate_chart(args: dict, **kw) -> str:
    chart_type = args.get("chart_type", "bar")
    title = args.get("title", "Chart")
    data = args.get("data", {})
    x_label = args.get("x_label", "")
    y_label = args.get("y_label", "")

    if not data:
        return json.dumps({"error": "Provide 'data' with labels and values"})

    logger.info("Generating chart: type=%s title=%r", chart_type, title)

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.ticker as mticker

        filename, filepath = _gen_filename("chart", "png")

        # CRYO dark theme
        plt.style.use("dark_background")
        fig, ax = plt.subplots(figsize=(10, 6), facecolor="#0a0e14")
        ax.set_facecolor("#0f1419")

        labels = data.get("labels", [])
        values = data.get("values", [])
        colors = data.get("colors", None)

        if not colors:
            cryo_colors = ["#00e5c7", "#22d3ee", "#34d399", "#a78bfa", "#fbbf24", "#f87171", "#60a5fa", "#fb923c"]
            colors = [cryo_colors[i % len(cryo_colors)] for i in range(len(labels))]

        if chart_type == "bar":
            bars = ax.bar(labels, values, color=colors, edgecolor="#1c2430", linewidth=0.5)
            ax.bar_label(bars, fmt="%.1f", fontsize=8, color="#e0e6ed")

        elif chart_type == "horizontal_bar":
            bars = ax.barh(labels, values, color=colors, edgecolor="#1c2430", linewidth=0.5)
            ax.bar_label(bars, fmt="%.1f", fontsize=8, color="#e0e6ed")

        elif chart_type == "pie":
            wedges, texts, autotexts = ax.pie(
                values, labels=labels, colors=colors, autopct="%1.1f%%",
                textprops={"fontsize": 9, "color": "#e0e6ed"},
                wedgeprops={"edgecolor": "#0a0e14", "linewidth": 1},
            )

        elif chart_type == "line":
            ax.plot(labels, values, color="#00e5c7", linewidth=2, marker="o", markersize=6, markerfacecolor="#22d3ee")
            ax.fill_between(range(len(labels)), values, alpha=0.1, color="#00e5c7")

        elif chart_type == "scatter":
            x_vals = data.get("x", labels)
            y_vals = data.get("y", values)
            sizes = data.get("sizes", [50] * len(x_vals))
            ax.scatter(x_vals, y_vals, s=sizes, c=colors[:len(x_vals)], alpha=0.7, edgecolors="#1c2430")

        elif chart_type == "heatmap":
            import numpy as np
            matrix = data.get("matrix", [])
            if matrix:
                im = ax.imshow(matrix, cmap="YlGnBu", aspect="auto")
                fig.colorbar(im, ax=ax, shrink=0.8)
                if labels:
                    ax.set_xticks(range(len(labels)))
                    ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=8)
                row_labels = data.get("row_labels", [])
                if row_labels:
                    ax.set_yticks(range(len(row_labels)))
                    ax.set_yticklabels(row_labels, fontsize=8)

        ax.set_title(title, fontsize=14, color="#00e5c7", pad=15, fontweight="bold")
        if x_label:
            ax.set_xlabel(x_label, fontsize=10, color="#6b7d93")
        if y_label:
            ax.set_ylabel(y_label, fontsize=10, color="#6b7d93")

        ax.tick_params(colors="#6b7d93", labelsize=9)
        for spine in ax.spines.values():
            spine.set_color("#2a3a4e")
        ax.grid(axis="y", alpha=0.15, color="#2a3a4e")

        plt.tight_layout()
        fig.savefig(str(filepath), dpi=150, bbox_inches="tight", facecolor="#0a0e14")
        plt.close(fig)

        logger.info("Chart generated: %s (%d bytes)", filename, filepath.stat().st_size)
        return json.dumps({
            "status": "success",
            "filename": filename,
            "path": str(filepath),
            "size_bytes": filepath.stat().st_size,
            "download_url": f"/api/reports/{filename}",
            "chart_type": chart_type,
        })

    except ImportError:
        logger.error("matplotlib not installed")
        return json.dumps({"error": "matplotlib not installed. Run: pip install matplotlib"})
    except Exception as e:
        logger.error("Chart generation failed: %s", e, exc_info=True)
        return json.dumps({"error": f"Chart generation failed: {e}"})


CHART_SCHEMA = {
    "name": "generate_chart",
    "description": "Generate publication-quality charts and visualizations. Supports bar, horizontal bar, pie, line, scatter, and heatmap charts. Use for visualizing research data, comparisons, distributions, and trends.",
    "parameters": {
        "type": "object",
        "properties": {
            "chart_type": {
                "type": "string",
                "enum": ["bar", "horizontal_bar", "pie", "line", "scatter", "heatmap"],
                "description": "Type of chart"
            },
            "title": {"type": "string", "description": "Chart title"},
            "data": {
                "type": "object",
                "description": "Chart data: {labels: [...], values: [...]} for most charts. For heatmap: {labels: [...], row_labels: [...], matrix: [[...]]}. For scatter: {x: [...], y: [...], sizes: [...]}",
            },
            "x_label": {"type": "string", "description": "X-axis label"},
            "y_label": {"type": "string", "description": "Y-axis label"},
        },
        "required": ["chart_type", "title", "data"],
    },
}

registry.register(
    name="generate_chart",
    toolset="cryo_reports",
    schema=CHART_SCHEMA,
    handler=_generate_chart,
    check_fn=lambda: True,
    emoji="📈",
)
